---
title: "Proyecto Gestión Financiera"
author: "Emilia HJaas"
format: html
editor: visual
bibliography: references.bib
lang: es-CL
---

```{r configuraciones}
#| message: false
#| echo: false
# Esto ya debiera estar cargado en el proyecto en posit.cloud
#devtools::install_github("business-science/tidyquant")
#Loads tidyquant, lubridate, xts, quantmod, TTR, and PerformanceAnalytics
library(tidyverse)
library(tidyquant)  
```

# Hito 1:

## Descripción Activo y Contexto

Fecha de entrega límite: Miércoles 25 de Septiembre 23:59.

### Definición

Nvidia Corporation, que  “es una empresa de software y fabless que diseña unidades de procesamiento de gráficos, interfaz de programación de aplicaciones para ciencia de datos y computación de alto rendimiento”. Según The Economist, “desde enero de 2023, el precio de las acciones del fabricante de chips ha subido en casi un 450 %. Con el valor total de sus acciones que se acerca a los 2 billones de dólares” y probablemente siga aumentando en el futuro. 

**Motivación**

La motivación que surge frente a este mercado y esta empresa es que la compañía Microsoft se asoció con la empresa Black Rock para invertir \$100 mil millones de dólares en proyectos de inteligencia artificial, según el diario financiero. Donde Nvidia será la empresa que proveerá todos los micro chips y tarjetas gráficas para este desarrollo. Esto es muy interesante, ya que Microsoft es un gigante tecnológico, Black Rock es la empresa de gestión de inversiones más grande del planeta, y Nvidia es la dominante en el mercado de microchips para la inteligencia artificial. Debido a esto nace mi motivación por investigar cómo se mueven las opciones de Nvidia, ya que gracias a estas millonarias inversiones, sus acciones podrían seguir aumentando a gran escala en el futuro.

### Contexto

Para el presente trabajo se investiga el sector de tarjetas gráficas y de procesamiento para la inteligencia artificial. En la actualidad la inteligencia artificial figura como un tipo de nueva revolución industrial, es algo reciente e innovador, es por eso que el procesamiento de información rápido y eficiente es indispensable. Los microchips son claves para la utilización de la inteligencia artificial, algunos dicen que actualmente se está viviendo una nueva “Guerra Fría” por estos microchips. Según un artículo publicado por la revista The Economist, Nvidia es la empresa líder que domina el mercado de micro chips. 

**Derivados**\
Debido a esto se analizará la empresa Nvidia Corporation, que  “es una empresa de software y fabless que diseña unidades de procesamiento de gráficos, interfaz de programación de aplicaciones para ciencia de datos y computación de alto rendimiento”. Según The Economist, “desde enero de 2023, el precio de las acciones del fabricante de chips ha subido en casi un 450 %. Con el valor total de sus acciones que se acerca a los 2 billones de dólares” y probablemente siga aumentando en el futuro.

Se utiliza una matriz binomial para analizar los posibles futuros valores del precio de la acción. 

−3.55. −66.31. −66.31

0.171465. 4409.615 4359.615

0.171465​ 4333.3585​ 4283.3585​[​]{.underline}

En la primera fila, se puede ver en el primer cuadrante el precio del bono en negativo, porque eso es lo que en el primer día debería el inversionista si compra el bono. En segundo cuadrante se ve a su vez lo que debería el comprador si compra el activo subyacente, y en tercer lugar se ve si el precio del activo inicialmente.En la segunda fila se aprecia el escenario positivo o up, de la acción. Representa un escenario positivo, es decir que el precio de la acción aumente.  En primer lugar se ve el valor del bono, que al ser una tasa libre de riesgo no se va a ver modificado en el escenario positivo o negativo. En segundo lugar, se ve el precio del activo subyacente en un escenario positivo. En tercer lugar se aprecia el precio del valor de la opción, que en este caso es positiva, y se observa una ganancia, ya que el precio de la acción es mayor al precio de ejercicio. En la tercera fila se observa el escenario negativo, o down. Donde en primer lugar se observa el precio del bono , el cual se mantiene constante debido a la tasa libre de riesgo como se dijo anteriormente. En segundo lugar se ve el escenario negativo en el precio del activo subyacente, pero aunque baja el precio, sigue siendo este mayor al valor del precio de ejercicio de la opción.  En tercer lugar, se ve el valor de la opción en un escenario negativo, donde a pesar de esto sigue siendo mayor al valor de la opción del precio de ejercicio. Se puede concluir que en escenarios tanto positivos como negativos la opción de compra significa una ganancia a la hora de invertir. Donde la opción entregará una ganancia mucho más significativa en comparación al bono.

**Bibliografía**

-   <https://images.nvidia.com/aem-dam/Solutions/homepage/pdf/NVIDIA-Story.pdf>

-   <https://www.economist.com/the-economist-explains/2024/02/27/why-do-nvidias-chips-dominate-the-ai-market?utm_medium=cpc.adword.pd&utm_source=google&ppccampaignID=19495686130&ppcadID=&utm_campaign=a.22brand_pmax&utm_content=conversion.direct-response.anonymous&gad_source=1&gbraid=0AAAAADf4AbahBCMk9na-1eVsF3nkLaq5C&gclid=CjwKCAjw6c63BhAiEiwAF0EH1FWYUBP-i1EJdTcRHcUqLWekvUQ0iswud2vMXlFU4WDG8JzQHcowDBoCTRgQAvD_BwE&gclsrc=aw.ds>

-   <https://www.lanacion.com.ar/tecnologia/que-son-los-chips-para-inteligencia-artificial-para-que-sirven-y-por-que-atraen-a-los-inversores-nid21072023/>

-   <https://www.df.cl/empresas/multinacionales/blackrock-y-microsoft-se-asocian-para-invertir-us-100-mil-millones-en>

-   <https://finance.yahoo.com/quote/NVDA/options/>

-   <https://finance.yahoo.com/quote/2YY%3DF/>

-   <https://www.newyorkfed.org/markets/reference-rates/sofr>
